#!/usr/bin/env python3
"""Build an offline, standalone review page; no font binaries or runtime bridge."""
from pathlib import Path
import base64,gzip
ROOT=Path(__file__).resolve().parent
css=(ROOT/'styles.css').read_text()
js='\n'.join((ROOT/name).read_text() for name in ('font-policy.js','tokens.js','design.js'))
mark=base64.b64encode((ROOT/'assets/tachiko-sheet-mark.svg').read_bytes()).decode()
preview='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tachiko Sheet — FES45 v3 preview</title><style>'''+css+'''
#studio{height:64px;display:flex;align-items:center;gap:20px;padding:0 16px;background:#252735;color:white;font:12px/18px system-ui,sans-serif;}#studio strong{font-weight:600;}#studio select{background:#fff;color:#252735;font:13px system-ui,sans-serif;min-height:32px;border-radius:6px;padding:0 8px;border:1px solid #aaa;}#studio .note{margin-left:auto;color:#eee;font-size:11px;}#studio .micro{font-size:11px;color:#ddd;}#studio select:focus-visible{outline:3px solid #afa4ff;outline-offset:2px;}@media(max-width:600px){#studio{gap:10px;padding:0 10px;}#studio .note,#studio .micro{display:none;}}@media(forced-colors:active){#studio{background:Canvas;color:CanvasText;}}
</style></head><body><aside id="studio" aria-label="Design-review controls, outside the product"><div><strong>FES45 v3 · Design preview</strong><div class="micro">Illustrative data. Product commands are not connected.</div></div><label for="specimen">State</label><select id="specimen"><option value="macbook-retina">Normal work</option><option value="state-mac-editing">Editing / unapplied draft</option><option value="state-mac-savefailed">Copy save failed</option><option value="state-mac-unknownretaineddraft">Unknown / retained draft</option></select><div class="note" id="fontNote">Loading local typography…</div></aside><main id="mount"></main><script>window.FES_ASSETS={'tachiko-sheet-mark.svg':'data:image/svg+xml;base64,'''+mark+"'};\n"+js+'''
(async()=>{
 try{await resolveFesFonts();document.getElementById('fontNote').textContent='Local design fonts · Not implementation authority';}
 catch(e){const st=document.createElement('style');st.textContent="html,body{font-family:Inter,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}.jp{font-family:'Hiragino Sans','Noto Sans CJK JP',sans-serif}.tc{font-family:'PingFang TC','Noto Sans CJK TC',sans-serif}[data-workbook-title]{font-family:Inter,-apple-system,sans-serif!important}";document.head.append(st);document.getElementById('fontNote').textContent='System-font preview · PNG evidence preserves exact typography';}
 const picker=document.getElementById('specimen'),mount=document.getElementById('mount');
 function draw(){const source=FES.scenarios.find(s=>s.name===picker.value);mount.replaceChildren();const w=Math.max(320,window.innerWidth),h=Math.max(200,window.innerHeight-64);const app=FES.shell(mount,{...source,W:w,H:h});requestAnimationFrame(()=>{(app.querySelector('.menu-item[data-state=KeyboardFocus]')||app.querySelector('.editor:not(:disabled)')||app.querySelector('[data-active=true][tabindex="0"]'))?.focus({preventScroll:true});});}
 picker.addEventListener('change',draw);let timer;window.addEventListener('resize',()=>{clearTimeout(timer);timer=setTimeout(draw,80);});draw();
})();
</script></body></html>'''
(ROOT/'preview-source.html').write_text(preview)
packed=base64.b64encode(gzip.compress(preview.encode(),compresslevel=9,mtime=0)).decode()
loader='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tachiko Sheet — FES45 v3</title></head><body style="font:14px system-ui;padding:24px"><p>Opening the offline Tachiko Sheet design preview…</p><script>
// Generated by build_preview.py. Full editable source and renderer are in the pinned bundle.
const packed="'''+packed+'''";
(async()=>{try{const bytes=Uint8Array.from(atob(packed),x=>x.charCodeAt(0));const html=await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).text();document.open();document.write(html);document.close();}catch(e){document.body.textContent='This browser cannot unpack the preview. Open preview-source.html from the complete bundle instead. '+String(e);}})();
</script></body></html>'''
(ROOT/'preview.html').write_text(loader)
print('Standalone preview bytes:',len(loader.encode()),'unpacked:',len(preview.encode()))
