// The Home example must load the unchanged seed fixture as opaque bytes.
// This checks the generated public copy byte-for-byte; it parses nothing.
import test from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { readFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { j4CanaryInventory, j4CanaryText } from "../fixtures/j4-catalog-sales.mjs";
import { salesCatalogInventory, salesCatalogText } from "../../scripts/sales-catalog-source.mjs";

const root = path.resolve(fileURLToPath(new URL("../..", import.meta.url)));
const seeds = path.join(root, "tests", "fixtures", "release-plan.roproj");
const generated = path.join(root, "public", "examples", "release-plan");
const j4Generated = path.join(root, "public", "examples", "j4-catalog-sales");
const salesGenerated = path.join(root, "public", "examples", "sales-catalog");
const inventory = [
  "manifest.json",
  "schemas.json",
  ...Array.from("0123456789abcdef", (shard) => `entities/${shard}.jsonl`),
];

test("the generated example copy is byte-identical to the unchanged seed fixture", async () => {
  const copy = spawnSync(process.execPath, [path.join(root, "scripts", "copy-example-fixture.mjs")], {
    cwd: root,
    encoding: "utf8",
  });
  assert.equal(copy.status, 0, copy.stderr);
  for (const entry of inventory) {
    const source = await readFile(path.join(seeds, entry));
    const target = await readFile(path.join(generated, entry));
    assert.ok(source.equals(target), `example copy differs from the seed fixture: ${entry}`);
  }
});

test("the generated J4 canary is byte-identical to the fixed qualified fixture", async () => {
  const copy = spawnSync(process.execPath, [path.join(root, "scripts", "copy-example-fixture.mjs")], {
    cwd: root,
    encoding: "utf8",
  });
  assert.equal(copy.status, 0, copy.stderr);
  for (const entry of j4CanaryInventory) {
    const target = await readFile(path.join(j4Generated, entry), "utf8");
    assert.equal(target, j4CanaryText[entry], `J4 canary copy differs from its fixed fixture: ${entry}`);
  }
});

test("the Sales product source changes only the exact J4 document title", async () => {
  const copy = spawnSync(process.execPath, [path.join(root, "scripts", "copy-example-fixture.mjs")], {
    cwd: root,
    encoding: "utf8",
  });
  assert.equal(copy.status, 0, copy.stderr);

  const inventoryHash = (source) => createHash("sha256").update(JSON.stringify(Object.entries(source).sort(([a], [b]) => a.localeCompare(b)))).digest("hex");
  assert.equal(inventoryHash(j4CanaryText), "d8ab17b0bc84f89fbc996beb730f0842ec2bf848d1ab4afd315cc34fa1195d2b", "the canonical J4 fixture inventory/hash is pinned");
  assert.equal(inventoryHash(salesCatalogText), "306e33992edaa39023b5f780dcc47c3dc1d19dc69d8dae0c68b810095a4b670f", "the generated product source inventory/hash is pinned");
  assert.deepEqual(salesCatalogInventory, j4CanaryInventory, "product and canonical source inventories have identical paths");

  const generatedPaths = async (directory) => {
    const { readdir } = await import("node:fs/promises");
    const walk = async (relative = "") => {
      const entries = await readdir(path.join(directory, relative), { withFileTypes: true });
      const found = [];
      for (const entry of entries) {
        const current = path.posix.join(relative, entry.name);
        if (entry.isDirectory()) found.push(...await walk(current));
        else found.push(current);
      }
      return found;
    };
    return (await walk()).sort();
  };
  assert.deepEqual(await generatedPaths(j4Generated), j4CanaryInventory, "canonical generated J4 has the pinned file inventory");
  assert.deepEqual(await generatedPaths(salesGenerated), j4CanaryInventory, "product source has exactly the canonical file inventory");

  for (const entry of j4CanaryInventory) {
    const canonical = await readFile(path.join(j4Generated, entry));
    const product = await readFile(path.join(salesGenerated, entry));
    assert.ok(canonical.equals(Buffer.from(j4CanaryText[entry])), `canonical J4 generated bytes changed: ${entry}`);
    assert.ok(product.equals(Buffer.from(salesCatalogText[entry])), `Sales product generated bytes differ from the source module: ${entry}`);
    if (entry !== "manifest.json") assert.ok(product.equals(canonical), `non-title source bytes differ: ${entry}`);
  }

  const canonicalManifest = j4CanaryText["manifest.json"];
  const productManifest = salesCatalogText["manifest.json"];
  assert.equal(productManifest.replace('"title": "Sales and catalog"', '"title": "Sheet J4 Catalog Sales"'), canonicalManifest, "raw manifest differs only by the title token");
  const canonicalMetadata = JSON.parse(canonicalManifest);
  const productMetadata = JSON.parse(productManifest);
  assert.equal(productMetadata.document.title, "Sales and catalog");
  productMetadata.document.title = canonicalMetadata.document.title;
  assert.deepEqual(productMetadata, canonicalMetadata, "parsed source metadata differs only by document title");
  assert.notEqual(productManifest, canonicalManifest, "the manifest is the only source file that differs");
});
