import type { CleanupOperation, CleanupPreview, ImportedProjection, ImportOptions, ImportSelection, InteropMetadata, NativeBudgetExportPresentation, NativeTrackerExportPresentation, SourceWorkbook, SpreadsheetExport, SpreadsheetFormat } from "./interop-protocol.ts";
import { type DesignerClient } from "./client.ts";
import type { FormulaCopy, TrackerCommand, BootstrapProjection, CanonicalTreeExport, CanonicalProjectFile, FieldBatchProjection, FieldTarget, OpenedProjection, OccurrenceProjection, PublicationProjection, KeyedGroupedSumDefinitionInput, KeyedGroupedSumProjection, KeyedGroupedSumPublishedProjection, ProjectExport, TableProjection } from "./protocol.ts";
export type DesignerWorkerFactory = () => Worker;
export declare class WorkerDesignerClient implements DesignerClient {
    #private;
    constructor(createWorker: DesignerWorkerFactory);
    newTracker(): Promise<OpenedProjection>;
    inspectSpreadsheet(bytes: ArrayBuffer, format: SpreadsheetFormat, csvOptions: ImportOptions): Promise<SourceWorkbook>;
    importSpreadsheet(bytes: ArrayBuffer, format: SpreadsheetFormat, csvOptions: ImportOptions, selection: ImportSelection, validate?: (candidate: ImportedProjection) => void): Promise<ImportedProjection>;
    inspectImportedProject(bytes: ArrayBuffer, metadata: InteropMetadata): Promise<OpenedProjection>;
    exportSpreadsheet(expectedRevision: string, metadata: InteropMetadata, format: SpreadsheetFormat, collection: string): Promise<SpreadsheetExport>;
    exportNativeTrackerSpreadsheet(expectedRevision: string, presentation: NativeTrackerExportPresentation, format: SpreadsheetFormat): Promise<SpreadsheetExport>;
    exportNativeBudgetSpreadsheet(expectedRevision: string, presentation: NativeBudgetExportPresentation, format: SpreadsheetFormat): Promise<SpreadsheetExport>;
    previewCleanup(expectedRevision: string, operation: CleanupOperation): Promise<CleanupPreview>;
    commitCleanup(expectedRevision: string, previewId: string): Promise<PublicationProjection>;
    newBudget(): Promise<OpenedProjection>;
    trackerCommand(request: TrackerCommand): Promise<PublicationProjection>;
    bootstrap(): Promise<BootstrapProjection>;
    inspectProject(bytes: ArrayBuffer): Promise<OpenedProjection>;
    openProject(bytes: ArrayBuffer): Promise<OpenedProjection>;
    openCanonicalTree(files: readonly CanonicalProjectFile[]): Promise<OpenedProjection>;
    openLocalDocument(bytes: ArrayBuffer): Promise<OpenedProjection>;
    exportProject(expectedRevision: string): Promise<ProjectExport>;
    exportCanonicalTree(expectedRevision: string): Promise<CanonicalTreeExport>;
    exportPortableRo(expectedRevision: string): Promise<ProjectExport>;
    verifyPortableRo(bytes: ArrayBuffer): Promise<void>;
    openPortableRo(bytes: ArrayBuffer): Promise<OpenedProjection>;
    observeOccurrence(): Promise<OccurrenceProjection>;
    closeProject(): Promise<void>;
    queryTable(collection: string): Promise<TableProjection>;
    queryFields(expectedRevision: string, fields: FieldTarget[]): Promise<FieldBatchProjection>;
    createKeyedGroupedSum(expectedRevision: string, definition: KeyedGroupedSumDefinitionInput): Promise<KeyedGroupedSumPublishedProjection>;
    queryKeyedGroupedSum(definitionId: string): Promise<KeyedGroupedSumProjection>;
    editNumber(expectedRevision: string, target: FieldTarget, input: string): Promise<PublicationProjection>;
    editText(expectedRevision: string, target: FieldTarget, value: string): Promise<PublicationProjection>;
    editBoolean(expectedRevision: string, target: FieldTarget, value: boolean): Promise<PublicationProjection>;
    editDate(expectedRevision: string, target: FieldTarget, value: string): Promise<PublicationProjection>;
    copyFormula(expectedRevision: string, request: FormulaCopy): Promise<PublicationProjection>;
    updateFormula(expectedRevision: string, target: FieldTarget, source: string): Promise<PublicationProjection>;
    close(): void;
}
export declare function freshOccurrenceId(): string;
